implemented robot class to substitute player
Teamprojekt-Roboarena-WS23/Roboarena pull request #8
Opened 2023-10-17 12:38 UTC by Phil-Ebsworth

2023-10-19 08:55 UTC, Ludwig-Uni requested changes
I left a few review comments.
There are also a couple of typos and quite some linter warnings.

(Perhaps we should change the Flake8 CI test to treat all of them as *errors*, so they get noticed on open pull requests?)

2023-10-19 08:55 UTC, Ludwig-Uni commented on Robot/robot.py
> +#definition of windowsize aufgrund fehlendes game state
I believe we should try to keep all code and comments in English

2023-10-19 08:55 UTC, Ludwig-Uni commented on Robot/robot.py
> +        self.line = (self.position, Vector2(self.position,self.position.y + self.radius / 2))
I find this definition rather hard to understand. I suggest changing `direction` to a number, perhaps `direction ∊ [0, 360)` and then drawing the line based on that?
At least `direction` doesn't sound like it should be tied to points in the coordinate plane.

2023-10-19 08:55 UTC, Ludwig-Uni commented on Robot/robot.py
> +class Robot():
Class should be called `BasicRobot` according to sprint specifications.

2023-10-19 10:12 UTC, Ludwig-Uni commented on Robot/robot.py
> +        self.line = (self.position, Vector2(self.position,self.position.y + self.radius / 2))
`direction ∊ (-180, 180]` now, because that's how pygame's polar coordinates work.

2023-10-21 12:12 UTC, KevinDwo requested changes
Seems good.

1 Change:
Right now the robot can go out of bounds.
In the robot class (l. 16 + 17) we have to change the minimum 0 --> 0 + radius.

2023-10-22 19:31 UTC, Ludwig-Uni commented
Good catch! I fixed that :​)

2023-10-23 19:09 UTC, KevinDwo approved these changes
Good.

2023-10-23 19:14 UTC, Ludwig-Uni approved these changes
Good for me as well now.

2023-10-23 19:14 UTC, merged