Arena
Teamprojekt-Roboarena-WS23/Roboarena pull request #9
Opened 2023-10-17 17:26 UTC by Phil-Ebsworth

Added code to implement a stage and draw it on sceen

2023-10-23 17:47 UTC, Ludwig-Uni requested changes
Overall this looks pretty good to me (except for the fact that my screen is not high enough to display 1000px), but some coordinates are duplicated in the code. I think that should be changed, then I'm good with this.

2023-10-23 17:47 UTC, Ludwig-Uni commented on Arena/terrain.py
> +        self.size = Vector2(50, 50)
This should either be passed to the `Terrain` class via game state, or removed from the game state, to avoid code duplication.

2023-10-23 17:47 UTC, Ludwig-Uni commented on Robot/robot.py
> +        self.position = Vector2(500, 500)  # Position in coordinates
The coordinates should be calculated according to the arena size inside the game state

2023-10-23 17:47 UTC, Ludwig-Uni commented on Arena/arena.py
> +        self.tileSize = pygame.Vector2(50, 50)
The `arenaSize` should either be passed via game state or removed from the game state.

The `tileSize` should definitely be removed from here and either be kept in the `Terrain` class only, or in the game state only.

2023-10-23 19:28 UTC, Ludwig-Uni approved these changes
Now it looks fine for me, waiting for @KevinDwo's review.

2023-10-24 05:24 UTC, KevinDwo approved these changes
Everything is fine.

2023-10-24 05:25 UTC, merged